front:
    resource: "@FrontBundle/Controller/"
    type:     annotation

homepage:
    resource: "@FrontBundle/Controller/"
    prefix:   /
    type:     annotation

user:
    resource: '@UserBundle/Resources/config/routing.yml'
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
